services:
  - type: web
    name: account-management-app
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: ENCRYPTION_KEY
        sync: false
      - key: SENDGRID_API_KEY
        sync: false
      - key: FROM_EMAIL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: ADMIN_RESET_KEY
        sync: false
